deploy_timeout: 3600
name: sert-cluster
gui_config_file: /tmp/cfg.yaml
# log_settings: logging.yaml
log_settings: logging.cfg
config_file: /tmp/netconfig.yaml

report:
  mail:
    smtp_server: "smtp.gmail.com"
    mail_to: "fuel-certification@mirantis.com"
    mail_from: "fuel-certification@mirantis.com"
    login: "fuel-certification@mirantis.com"

cluster_desc:
    name: certification_cluster
    deployment_mode: ha_compact
    net_provider: neutron_vlan
    libvirt_type: kvm
    release: "2"

    nodes:
        - controller, 1
        - compute + cinder, 2+
